"""
Django settings for flightlog project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEBUG = os.environ.get("DJANGO_DEBUG", "1") not in ("", "0", "false", "False")

# SECURITY WARNING: keep the secret key used in production secret!
_secret = (os.environ.get("DJANGO_SECRET_KEY") or "").strip()
SECRET_KEY = (
    _secret
    if _secret
    else 'django-insecure-llc)&+8tseiqhuz294^z@ckjboqouyc+$)s#z885=2aq%7yw72'
)

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()] if _allowed else []

CSRF_TRUSTED_ORIGINS = [
    x.strip()
    for x in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if x.strip()
]

# En contenedores o despliegues simples: servir /media desde Django (no usar en origen público de alto tráfico).
SERVE_MEDIA = os.environ.get("DJANGO_SERVE_MEDIA", "0") in ("1", "true", "True")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'users',
    'aircraft',
    'airports',
    'logbook',
    'charts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flightlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flightlog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_sqlite_path = os.environ.get("DJANGO_SQLITE_PATH")
_db_name = Path(_sqlite_path) if _sqlite_path else (BASE_DIR / "db.sqlite3")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _db_name,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
]

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
if not DEBUG:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    }

# Archivos subidos (PDF de cartas, etc.) — solo desarrollo; en producción el servidor web sirve MEDIA_ROOT
# Prefijo con "/" para que las URLs sean de sitio (`/media/...`) y se resuelvan bien desde cualquier ruta.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Permitir incrustar en iframe recursos del mismo origen (p. ej. PDF bajo /media/ en el visor de cartas).
# El valor por defecto de Django es DENY y el visor del navegador no muestra el PDF en el iframe.
X_FRAME_OPTIONS = "SAMEORIGIN"

LOGIN_URL = "users:login"
LOGIN_REDIRECT_URL = "logbook:dashboard"
LOGOUT_REDIRECT_URL = "users:login"
