# Generated by Django 6.0.4 on 2026-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=32)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['registration'],
            },
        ),
    ]
