# Generated by Django 6.0.4 on 2026-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['icao_code'],
            },
        ),
    ]
