# Generated by Django 6.0.4 on 2026-04-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('block_off', models.TimeField(help_text='Hora de salida (bloque motor / rodaje según tu criterio).')),
                ('block_on', models.TimeField(help_text='Hora de llegada.')),
                ('total_time', models.DurationField(editable=False, help_text='Calculado al guardar a partir de block_off y block_on.')),
                ('remarks', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs', to='aircraft.aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='airports.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='airports.airport')),
            ],
            options={
                'ordering': ['-date', '-block_off', '-id'],
            },
        ),
    ]
