# Generated by Django 6.0.4 on 2026-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_flightlog_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightlog',
            options={'ordering': ['-planned_date', '-id']},
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='planned_date',
            field=models.DateField(help_text='Fecha prevista o fecha del vuelo planificado.'),
        ),
    ]
